export const propsClimateСontrol = [
  {
    id: "sunnyMoon",
    cloudAmount: 2,
    minRandomTopAndLeft: 10,
    maxRandomTopAndLeft: 120,
    timeMinRandomMovements: 26,
    timeMaxRandomMovements: 80,
    numberCloudLayers: 10,
    minRandomTopAndLeftLocationCloudLayers: 14,
    maxRandomTopAndLeftLocationCloudLayers: 40,
    timeMinRandomCloudLayers: 8,
    timeMaxRandomCloudLayers: 12,
  },
  {
    id: "cloudyWithSunMoon",
    cloudAmount: 2,
    minRandomTopAndLeft: 10,
    maxRandomTopAndLeft: 120,
    timeMinRandomMovements: 26,
    timeMaxRandomMovements: 80,
    numberCloudLayers: 10,
    minRandomTopAndLeftLocationCloudLayers: 14,
    maxRandomTopAndLeftLocationCloudLayers: 40,
    timeMinRandomCloudLayers: 8,
    timeMaxRandomCloudLayers: 12,
  },
  {
    id: "cloudy",
    cloudAmount: 2,
    minRandomTopAndLeft: 10,
    maxRandomTopAndLeft: 120,
    timeMinRandomMovements: 26,
    timeMaxRandomMovements: 80,
    numberCloudLayers: 10,
    minRandomTopAndLeftLocationCloudLayers: 14,
    maxRandomTopAndLeftLocationCloudLayers: 40,
    timeMinRandomCloudLayers: 8,
    timeMaxRandomCloudLayers: 12,
  },
  {
    id: "rainy",
    cloudAmount: 2,
    minRandomTopAndLeft: 30,
    maxRandomTopAndLeft: 120,
    timeMinRandomMovements: 26,
    timeMaxRandomMovements: 80,
    numberCloudLayers: 10,
    minRandomTopAndLeftLocationCloudLayers: 14,
    maxRandomTopAndLeftLocationCloudLayers: 40,
    timeMinRandomCloudLayers: 8,
    timeMaxRandomCloudLayers: 12,
    amountRainClouds: 20,
    minRandomLeftRain: 0,
    maxRandomLeftRain: 32,
    timeMinRandomRain: 10,
    timeMaxRandomRain: 20,
  },
  {
    id: "cloudyWithRainAndLightning",
    cloudAmount: 2,
    minRandomTopAndLeft: 50,
    maxRandomTopAndLeft: 120,
    timeMinRandomMovements: 26,
    timeMaxRandomMovements: 80,
    numberCloudLayers: 10,
    minRandomTopAndLeftLocationCloudLayers: 14,
    maxRandomTopAndLeftLocationCloudLayers: 40,
    timeMinRandomCloudLayers: 8,
    timeMaxRandomCloudLayers: 12,
    amountRainClouds: 20,
    minRandomLeftRain: 0,
    maxRandomLeftRain: 32,
    timeMinRandomRain: 10,
    timeMaxRandomRain: 20,
  },
  {
    id: "snowy",
    cloudAmount: 2,
    minRandomTopAndLeft: -80,
    maxRandomTopAndLeft: 120,
    timeMinRandomMovements: 26,
    timeMaxRandomMovements: 80,
    numberCloudLayers: 10,
    minRandomTopAndLeftLocationCloudLayers: 14,
    maxRandomTopAndLeftLocationCloudLayers: 40,
    timeMinRandomCloudLayers: 8,
    timeMaxRandomCloudLayers: 12,
    amountRainClouds: 20,
    minRandomLeftRain: 0,
    maxRandomLeftRain: 32,
    timeMinRandomRain: 10,
    timeMaxRandomRain: 20,
  },
];
